name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 16.170.183.80
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Lost-and-Found-Portal
            git pull origin main
            /usr/bin/mvn clean package -DskipTests

            echo "Restarting app..."
            sudo systemctl restart lostfound

            echo "Status check..."
            sudo systemctl status lostfound